import type { DiscoveryMap, PpaFacts, PpaState } from "./ppaTypes";

const blankDiscovery: DiscoveryMap = {
  businessContext: "unknown",
  desiredWork: "unknown",
  unwantedWork: "unknown",
  economicFit: "unknown",
  businessDirection: "unknown",
  bestCustomerPattern: "unknown",
  buyingTrigger: "unknown",
  whyNow: "unknown",
  desiredOutcome: "unknown",
  buyerFears: "unknown",
  decisionCriteria: "unknown",
  alternatives: "unknown",
  premiumBuyingLogic: "unknown",
  poorFitPattern: "unknown",
  choiceReasons: "unknown",
  experienceDifferences: "unknown",
  differentiatorMechanisms: "unknown",
  buyerRelevance: "unknown",
  differentiatorProof: "unknown",
  commodityPressure: "unknown",
  unwantedIdentity: "unknown",
  lostBusinessSignals: "unknown",
  voiceOfCustomer: "unknown",
  trustAssets: "unknown",
  competitiveSeparation: "unknown",
  positioningReadiness: "unknown",
};

const blankFacts: PpaFacts = {
  companyName: "",
  businessSummary: "",
  geography: "",
  currentWork: [],
  desiredWork: [],
  unwantedWork: [],
  typicalProjectValue: "",
  idealProjectValue: "",
  direction: "",
  bestCustomerPatterns: [],
  buyingTriggers: [],
  whyNow: [],
  desiredOutcomes: [],
  buyerFears: [],
  decisionCriteria: [],
  alternatives: [],
  premiumBuyingLogic: [],
  poorFitPatterns: [],
  choiceReasons: [],
  experienceDifferences: [],
  differentiators: [],
  differentiatorProof: [],
  commodityPressure: [],
  unwantedIdentity: [],
  wantedIdentity: [],
  lostBusinessSignals: [],
  voiceOfCustomerExact: [],
  voiceOfCustomerThemes: [],
  trustAssets: [],
  competitors: [],
  sourceNotes: [],
  unresolved: [],
};

export function createInitialState(): PpaState {
  return {
    stage: "business_direction",
    progress: 3,
    questionCount: 0,
    discovery: { ...blankDiscovery },
    facts: structuredClone(blankFacts),
    conciseSummary: "No discovery completed yet.",
  };
}
